apiVersion: v1
kind: Pod
metadata:
  name: oob-pic24f-lcd-curiosity
spec:
  containers:
    - name: oob-pic24f-lcd-curiosity
      image: artifacts.microchip.com:7999/microchip/citd/xc16-mplabx:1.36B-5.20
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 8Gi
